## Grupo X 
### 

Objetivo: Predicción de la variación mensual del precio del petróleo crudo Brent mediante un índice de riesgo geopolítico.

¿Existe una relación entre el aumento del riesgo geopolítico y las variaciones mensuales del precio del Brent?

In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

In [21]:
brent_file = pd.ExcelFile("./data/raw/brent_eia.xls")
gpr_file = pd.ExcelFile("./data/raw/gpr_monthly.xls")

print("Hojas Brent:", brent_file.sheet_names)
print("Hojas GPR:", gpr_file.sheet_names)

Hojas Brent: ['Sheet1']
Hojas GPR: ['Contents', 'Data 1']

In [24]:
brent_raw = pd.read_excel(
    "./data/raw/brent_eia.xls",
    sheet_name=brent_file.sheet_names[0],
    header=None
)

gpr_raw = pd.read_excel(
    "./data/raw/gpr_monthly.xls",
    sheet_name=gpr_file.sheet_names[1],
    header=None
)

display(brent_raw.head(10))
display(gpr_raw.head(10))

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,month,GPR,GPRT,GPRA,GPRH,GPRHT,GPRHA,SHARE_GPR,N10,SHARE_GPRH,...,GPRHC_TUN,GPRHC_TUR,GPRHC_TWN,GPRHC_UKR,GPRHC_USA,GPRHC_VEN,GPRHC_VNM,GPRHC_ZAF,var_name,var_label
1,1900-01-01 00:00:00,NaN,NaN,NaN,87.927849,64.717491,110.453522,NaN,NaN,3.171932,...,0,0.03884,0,0,2.718799,0.051787,0.012947,1.152253,month,Date (year/month)
2,1900-02-01 00:00:00,NaN,NaN,NaN,86.56649,71.936844,96.250488,NaN,NaN,3.122822,...,0,0.125471,0,0,2.732469,0.027882,0,1.143176,GPR,Recent GPR (Index: 1985:2019=100)
3,1900-03-01 00:00:00,NaN,NaN,NaN,72.140701,57.475853,84.499428,NaN,NaN,2.602422,...,0,0.180366,0,0,2.151507,0.025767,0,0.86318,GPRT,Recent GPR Threats (Index: 1985:2019=100)
4,1900-04-01 00:00:00,NaN,NaN,NaN,54.419449,37.326603,65.858208,NaN,NaN,1.963141,...,0,0.066774,0,0,1.776175,0,0,0.641026,GPRA,Recent GPR Acts (Index: 1985:2019=100)
5,1900-05-01 00:00:00,NaN,NaN,NaN,64.405197,48.200008,74.373955,NaN,NaN,2.32337,...,0,0.081522,0,0,1.970109,0.013587,0,0.788043,GPRH,Historical GPR (Index: 1900:2019=100)
6,1900-06-01 00:00:00,NaN,NaN,NaN,83.610252,70.006577,93.977692,NaN,NaN,3.016178,...,0.01371,0.109679,0.02742,0,2.72827,0.02742,0.04113,0.671785,GPRHT,Historical GPR Threats (Index: 1900:2019=100)
7,1900-07-01 00:00:00,NaN,NaN,NaN,108.571121,87.062378,125.709084,NaN,NaN,3.916622,...,0,0.146044,0.03983,0,3.544875,0.026553,0.026553,0.292087,GPRHA,Historical GPR Acts (Index: 1900:2019=100)
8,1900-08-01 00:00:00,NaN,NaN,NaN,108.502815,63.841644,149.760986,NaN,NaN,3.914158,...,0.013497,0.080983,0.040491,0,3.549737,0.026994,0.013497,0.242948,SHARE_GPR,Percent of Recent GPR Articles
9,1900-09-01 00:00:00,NaN,NaN,NaN,62.813301,54.698414,67.581779,NaN,NaN,2.265943,...,0,0.040706,0.013569,0,2.008141,0.013569,0,0.176391,N10,"Number of articles (10 recent newspapers, 1985-)"

                     0                                                  1
0     Back to Contents  Data 1: Europe Brent Spot Price FOB (Dollars p...
1            Sourcekey                                              RBRTE
2                 Date   Europe Brent Spot Price FOB (Dollars per Barrel)
3  1987-05-15 00:00:00                                              18.58
4  1987-06-15 00:00:00                                              18.86
5  1987-07-15 00:00:00                                              19.86
6  1987-08-15 00:00:00                                              18.98
7  1987-09-15 00:00:00                                              18.31
8  1987-10-15 00:00:00                                              18.76
9  1987-11-15 00:00:00                                              17.78

AttributeError: 'ExcelFile' object has no attribute 'head'